/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BasicPaint;

import java.awt.Color;

/**
 *
 * @author lucypher
 */
public class VentanaPrincipal extends javax.swing.JFrame {


    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        GrupoBotonesSuperior = new javax.swing.ButtonGroup();
        displayHerramienta = new javax.swing.JLabel();
        PanelCentral = new javax.swing.JPanel();
        PanelSuperior = new javax.swing.JPanel();
        BarraHerramientas = new javax.swing.JToolBar();
        BotonLapiz = new javax.swing.JToggleButton();
        BotonLinea = new javax.swing.JToggleButton();
        BotonCuadrado = new javax.swing.JToggleButton();
        BotonCirculo = new javax.swing.JToggleButton();
        PanelInferior = new javax.swing.JPanel();
        PanelBotones = new javax.swing.JPanel();
        BotonNegro = new javax.swing.JButton();
        BotonRojo = new javax.swing.JButton();
        BotonAzul = new javax.swing.JButton();
        BotonVerde = new javax.swing.JButton();
        BotonAmarillo = new javax.swing.JButton();
        BotonBlanco = new javax.swing.JButton();
        PanelRelleno = new javax.swing.JPanel();
        CheckBoxRelleno = new javax.swing.JCheckBox();
        lienzo = new BasicPaint.Lienzo();
        Menu = new javax.swing.JMenuBar();
        MenuArchivo = new javax.swing.JMenu();
        MenuItemNuevo = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        MenuEdicion = new javax.swing.JMenu();
        BarraEstadoCheckbox = new javax.swing.JCheckBoxMenuItem();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PaintBasico");
        displayHerramienta.setText("Herramienta seleccionada");
        getContentPane().add(displayHerramienta, java.awt.BorderLayout.PAGE_END);
        PanelCentral.setLayout(new java.awt.BorderLayout());
        PanelSuperior.setPreferredSize(new java.awt.Dimension(436, 35));
        PanelSuperior.setLayout(null);
        BarraHerramientas.setBorder(null);
        BarraHerramientas.setRollover(true);
        GrupoBotonesSuperior.add(BotonLapiz);
        BotonLapiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BasicPaint/Lapiz.gif"))); // NOI18N
        BotonLapiz.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BotonLapizFocusGained(evt);
            }
        });
        BarraHerramientas.add(BotonLapiz);
        GrupoBotonesSuperior.add(BotonLinea);
        BotonLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BasicPaint/Linea.gif"))); // NOI18N
        BotonLinea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BotonLineaFocusGained(evt);
            }
        });
        BarraHerramientas.add(BotonLinea);
        GrupoBotonesSuperior.add(BotonCuadrado);
        BotonCuadrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BasicPaint/Rectangulo.gif"))); // NOI18N
        BotonCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCuadradoActionPerformed(evt);
            }
        });
        BarraHerramientas.add(BotonCuadrado);
        GrupoBotonesSuperior.add(BotonCirculo);
        BotonCirculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BasicPaint/Ovalo.gif"))); // NOI18N
        BotonCirculo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BotonCirculoFocusGained(evt);
            }
        });
        BarraHerramientas.add(BotonCirculo);
        PanelSuperior.add(BarraHerramientas);
        BarraHerramientas.setBounds(0, 0, 240, 40);
        PanelCentral.add(PanelSuperior, java.awt.BorderLayout.PAGE_START);
        PanelInferior.setPreferredSize(new java.awt.Dimension(436, 25));
        PanelInferior.setLayout(new java.awt.BorderLayout());
        PanelBotones.setPreferredSize(new java.awt.Dimension(150, 50));
        PanelBotones.setRequestFocusEnabled(false);
        PanelBotones.setVerifyInputWhenFocusTarget(false);
        PanelBotones.setLayout(null);
        BotonNegro.setBackground(new java.awt.Color(1, 1, 1));
        BotonNegro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNegroActionPerformed(evt);
            }
        });
        PanelBotones.add(BotonNegro);
        BotonNegro.setBounds(0, 0, 19, 19);
        BotonRojo.setBackground(new java.awt.Color(255, 3, 0));
        BotonRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRojoActionPerformed(evt);
            }
        });
        PanelBotones.add(BotonRojo);
        BotonRojo.setBounds(20, 0, 19, 19);
        BotonAzul.setBackground(new java.awt.Color(0, 32, 255));
        BotonAzul.setForeground(new java.awt.Color(16, 0, 234));
        BotonAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAzulActionPerformed(evt);
            }
        });
        PanelBotones.add(BotonAzul);
        BotonAzul.setBounds(40, 0, 19, 19);
        BotonVerde.setBackground(new java.awt.Color(0, 255, 0));
        BotonVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVerdeActionPerformed(evt);
            }
        });
        PanelBotones.add(BotonVerde);
        BotonVerde.setBounds(60, 0, 19, 19);
        BotonAmarillo.setBackground(new java.awt.Color(255, 239, 0));
        BotonAmarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAmarilloActionPerformed(evt);
            }
        });
        PanelBotones.add(BotonAmarillo);
        BotonAmarillo.setBounds(80, 0, 19, 19);
        BotonBlanco.setBackground(new java.awt.Color(254, 254, 254));
        BotonBlanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBlancoActionPerformed(evt);
            }
        });
        PanelBotones.add(BotonBlanco);
        BotonBlanco.setBounds(100, 0, 19, 19);
        PanelInferior.add(PanelBotones, java.awt.BorderLayout.LINE_START);
        CheckBoxRelleno.setText("Relleno");
        CheckBoxRelleno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CheckBoxRellenoItemStateChanged(evt);
            }
        });
        CheckBoxRelleno.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                CheckBoxRellenoStateChanged(evt);
            }
        });
        CheckBoxRelleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxRellenoActionPerformed(evt);
            }
        });
        javax.swing.GroupLayout PanelRellenoLayout = new javax.swing.GroupLayout(PanelRelleno);
        PanelRelleno.setLayout(PanelRellenoLayout);
        PanelRellenoLayout.setHorizontalGroup(
            PanelRellenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRellenoLayout.createSequentialGroup()
                      .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                      .addComponent(CheckBoxRelleno)
                      .addContainerGap())
        );
        PanelRellenoLayout.setVerticalGroup(
            PanelRellenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRellenoLayout.createSequentialGroup()
                      .addGap(0, 3, Short.MAX_VALUE)
                      .addComponent(CheckBoxRelleno))
        );
        PanelInferior.add(PanelRelleno, java.awt.BorderLayout.LINE_END);
        PanelCentral.add(PanelInferior, java.awt.BorderLayout.PAGE_END);
        lienzo.setBackground(new java.awt.Color(254, 254, 254));
        javax.swing.GroupLayout lienzoLayout = new javax.swing.GroupLayout(lienzo);
        lienzo.setLayout(lienzoLayout);
        lienzoLayout.setHorizontalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
        );
        lienzoLayout.setVerticalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );
        PanelCentral.add(lienzo, java.awt.BorderLayout.CENTER);
        getContentPane().add(PanelCentral, java.awt.BorderLayout.CENTER);
        MenuArchivo.setText("Archivo");
        MenuItemNuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK));
        MenuItemNuevo.setText("Nuevo");
        MenuItemNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemNuevoActionPerformed(evt);
            }
        });
        MenuArchivo.add(MenuItemNuevo);
        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuArchivo.add(jMenuItem1);
        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("Guardar");
        MenuArchivo.add(jMenuItem2);
        Menu.add(MenuArchivo);
        MenuEdicion.setText("Edicion");
        BarraEstadoCheckbox.setSelected(true);
        BarraEstadoCheckbox.setText("Ver barra de estado");
        BarraEstadoCheckbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BarraEstadoCheckboxMouseClicked(evt);
            }
        });
        BarraEstadoCheckbox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                BarraEstadoCheckboxItemStateChanged(evt);
            }
        });
        MenuEdicion.add(BarraEstadoCheckbox);
        Menu.add(MenuEdicion);
        setJMenuBar(Menu);
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void BarraEstadoCheckboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_BarraEstadoCheckboxItemStateChanged
        if(BarraEstadoCheckbox.getState()==true) {
            displayHerramienta.setVisible(true);
        }
        if(BarraEstadoCheckbox.getState()==false) {
            displayHerramienta.setVisible(false);
        }
    }//GEN-LAST:event_BarraEstadoCheckboxItemStateChanged

    private void BarraEstadoCheckboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraEstadoCheckboxMouseClicked
    }//GEN-LAST:event_BarraEstadoCheckboxMouseClicked

    private void BotonLapizFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BotonLapizFocusGained
        displayHerramienta.setText("Lapiz");
        lienzo.setHerramientaSeleccionada(Herramientas.Lapiz);
    }//GEN-LAST:event_BotonLapizFocusGained

    private void BotonLineaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BotonLineaFocusGained
        displayHerramienta.setText("Linea");
        lienzo.setHerramientaSeleccionada(Herramientas.Linea);
    }//GEN-LAST:event_BotonLineaFocusGained

    private void BotonCirculoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BotonCirculoFocusGained
        displayHerramienta.setText("Circulo");
        lienzo.setHerramientaSeleccionada(Herramientas.Circulo);
    }//GEN-LAST:event_BotonCirculoFocusGained

    private void BotonCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCuadradoActionPerformed
        displayHerramienta.setText("Cuadrado");
        lienzo.setHerramientaSeleccionada(Herramientas.Cuadrado);
    }//GEN-LAST:event_BotonCuadradoActionPerformed

    private void MenuItemNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemNuevoActionPerformed
        lienzo.Reset();
    }//GEN-LAST:event_MenuItemNuevoActionPerformed

    private void CheckBoxRellenoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_CheckBoxRellenoStateChanged
    }//GEN-LAST:event_CheckBoxRellenoStateChanged

    private void CheckBoxRellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxRellenoActionPerformed
    }//GEN-LAST:event_CheckBoxRellenoActionPerformed

    private void CheckBoxRellenoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CheckBoxRellenoItemStateChanged
        if(CheckBoxRelleno.isSelected())
            lienzo.setRelleno(true);
        else
            lienzo.setRelleno(false);
    }//GEN-LAST:event_CheckBoxRellenoItemStateChanged

    private void BotonNegroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNegroActionPerformed
        lienzo.setColor(Color.BLACK);
    }//GEN-LAST:event_BotonNegroActionPerformed

    private void BotonRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRojoActionPerformed
        lienzo.setColor(Color.RED);
    }//GEN-LAST:event_BotonRojoActionPerformed

    private void BotonAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAzulActionPerformed
        lienzo.setColor(Color.BLUE);
    }//GEN-LAST:event_BotonAzulActionPerformed

    private void BotonVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVerdeActionPerformed
        lienzo.setColor(Color.GREEN);
    }//GEN-LAST:event_BotonVerdeActionPerformed

    private void BotonAmarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAmarilloActionPerformed
        lienzo.setColor(Color.YELLOW);
    }//GEN-LAST:event_BotonAmarilloActionPerformed

    private void BotonBlancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBlancoActionPerformed
        lienzo.setColor(Color.WHITE);
    }//GEN-LAST:event_BotonBlancoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem BarraEstadoCheckbox;
    private javax.swing.JToolBar BarraHerramientas;
    private javax.swing.JButton BotonAmarillo;
    private javax.swing.JButton BotonAzul;
    private javax.swing.JButton BotonBlanco;
    private javax.swing.JToggleButton BotonCirculo;
    private javax.swing.JToggleButton BotonCuadrado;
    private javax.swing.JToggleButton BotonLapiz;
    private javax.swing.JToggleButton BotonLinea;
    private javax.swing.JButton BotonNegro;
    private javax.swing.JButton BotonRojo;
    private javax.swing.JButton BotonVerde;
    private javax.swing.JCheckBox CheckBoxRelleno;
    private javax.swing.ButtonGroup GrupoBotonesSuperior;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu MenuArchivo;
    private javax.swing.JMenu MenuEdicion;
    private javax.swing.JMenuItem MenuItemNuevo;
    private javax.swing.JPanel PanelBotones;
    private javax.swing.JPanel PanelCentral;
    private javax.swing.JPanel PanelInferior;
    private javax.swing.JPanel PanelRelleno;
    private javax.swing.JPanel PanelSuperior;
    private javax.swing.JLabel displayHerramienta;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private BasicPaint.Lienzo lienzo;
    // End of variables declaration//GEN-END:variables
}
